-- QMate table schema for PostgreSQL / pgAdmin.
-- First run create_database.sql while connected to the postgres database.
-- Then connect to qmate and run this file in Query Tool.
-- geofence_point format: [[latitude, longitude], ...] with exactly four points.

BEGIN;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(160) NOT NULL,
    phone VARCHAR(32) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'citizen'
        CHECK (role IN ('citizen', 'employee', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE government_office (
    gov_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gov_name VARCHAR(180) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(32),
    geofence_point JSONB NOT NULL,
    buffer_time_minutes INTEGER NOT NULL DEFAULT 0,
    created_timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (user_id),
    gov_id BIGINT NOT NULL REFERENCES government_office (gov_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE holiday (
    holiday_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    "date" DATE NOT NULL,
    remarks TEXT,
    day VARCHAR(16),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE counters (
    counter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counter_number INTEGER NOT NULL,
    employee_id BIGINT NOT NULL REFERENCES employees (employee_id),
    counter_name VARCHAR(120) NOT NULL
);

CREATE TABLE services (
    service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(160) NOT NULL,
    average_service_minutes INTEGER NOT NULL CHECK (average_service_minutes > 0),
    counter_id BIGINT NOT NULL REFERENCES counters (counter_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE queue (
    queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counter_id BIGINT NOT NULL REFERENCES counters (counter_id),
    queue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE queue_members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id BIGINT NOT NULL REFERENCES queue (queue_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    service_id BIGINT NOT NULL REFERENCES services (service_id),
    token_number VARCHAR(32) NOT NULL,
    q_position INTEGER NOT NULL CHECK (q_position > 0),
    status VARCHAR(16) NOT NULL DEFAULT 'not arrived'
        CHECK (status IN ('not arrived', 'arrived', 'serving', 'completed', 'late', 'no_show', 'cancelled')),
    "isArrived" BOOLEAN NOT NULL DEFAULT FALSE,
    "date" DATE NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    arrived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (queue_id, token_number),
    UNIQUE (queue_id, q_position)
);

CREATE TABLE citizen_locations (
    loc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES queue_members (member_id),
    latitude NUMERIC(9, 6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9, 6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    accuracy_meters NUMERIC(8, 2) NOT NULL CHECK (accuracy_meters >= 0),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE completed_requests (
    com_req_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES queue_members (member_id),
    queue_id BIGINT NOT NULL REFERENCES queue (queue_id),
    counter_id BIGINT NOT NULL REFERENCES counters (counter_id),
    service_id BIGINT NOT NULL REFERENCES services (service_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    employee_id BIGINT NOT NULL REFERENCES employees (employee_id),
    execution_order INTEGER NOT NULL CHECK (execution_order > 0),
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    total_duration INTERVAL,
    estimated_service_time INTERVAL,
    actual_service_time INTERVAL,
    CHECK (end_at >= start_at)
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (user_id),
    members_id BIGINT REFERENCES queue_members (member_id),
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    CHECK ((is_read AND read_at IS NOT NULL) OR (NOT is_read AND read_at IS NULL))
);

-- Index foreign keys and common queue, location, reporting, and notification lookups.
CREATE INDEX employees_gov_id_idx ON employees (gov_id);
CREATE INDEX holiday_user_date_idx ON holiday (user_id, "date");
CREATE INDEX counters_employee_id_idx ON counters (employee_id);
CREATE INDEX services_counter_id_idx ON services (counter_id);
CREATE INDEX queue_counter_date_idx ON queue (counter_id, queue_date);
CREATE INDEX queue_members_next_idx
    ON queue_members (queue_id, q_position)
    WHERE "isArrived" = TRUE;
CREATE INDEX queue_members_user_history_idx
    ON queue_members (user_id, joined_at DESC);
CREATE INDEX queue_members_service_id_idx ON queue_members (service_id);
CREATE INDEX citizen_locations_member_recorded_idx
    ON citizen_locations (member_id, recorded_at DESC);
CREATE INDEX completed_requests_employee_end_idx
    ON completed_requests (employee_id, end_at DESC);
CREATE INDEX completed_requests_counter_end_idx
    ON completed_requests (counter_id, end_at DESC);
CREATE INDEX completed_requests_service_end_idx
    ON completed_requests (service_id, end_at DESC);
CREATE INDEX notifications_unread_user_idx
    ON notifications (user_id, created_at DESC)
    WHERE is_read = FALSE;
CREATE INDEX notifications_members_id_idx ON notifications (members_id);

COMMIT;
